#Metric in more than 1 Dimension

PREFIX daq:<http://purl.org/eis/vocab/daq#>
PREFIX rdf:<http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs:<http://www.w3.org/2000/01/rdf-schema#>
PREFIX xsd:<http://www.w3.org/2001/XMLSchema#>

SELECT DISTINCT ?dimension ?metric {
	?dimension rdfs:subClassOf daq:Dimension .

	?hasMetric rdfs:domain ?dimension .
	?hasMetric rdfs:range  ?metric.
	{
		SELECT DISTINCT ?metric {
			?metric rdfs:subClassOf daq:Metric .
			
			?hasMetric rdfs:domain ?dim .
			?hasMetric rdfs:range  ?metric.
		
			?hasMetric rdfs:subPropertyOf daq:hasMetric .
		}
		GROUP BY ?metric
		HAVING(count(?metric) > 1)
	}
}