#Dimension in more than 1 Category

SELECT DISTINCT ?dimension  (COUNT (?category) as ?cat) {
	?category rdfs:subClassOf daq:Category .
	
	?hasDimension rdfs:domain ?category .
	?hasDimension rdfs:range ?dimension .
		
	{
		SELECT DISTINCT ?dimension {
			?dimension rdfs:subClassOf daq:Dimension .
			
			?hasDimension rdfs:domain ?cat .
			?hasDimension rdfs:range ?dimension .
		
			?hasDimension rdfs:subPropertyOf daq:hasDimension .
		}
		GROUP BY ?dimension
		HAVING(count(?dimension) > 1)
	}
} GROUP BY ?dimension